# Azure Pipeline Configuration

# Pipeline name and trigger conditions
name: BMI Test, Trigger

# Activation conditions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs to execute after activation
jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Recommended: 'ubuntu-latest' or specific versions like 'ubuntu-20.04'

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Docker buildx (to use advanced Docker build features)
      - name: Set up Docker builder
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
